<script setup lang="ts">
/**
 * ============================================================================
 * Page: Simulation Logs (/admin/simulation-logs)
 * ============================================================================
 * Real-time activity feed of the simulation engine.
 */
import { h } from 'vue'
import { UBadge, UButton } from '#components'
import type { AppLog } from '~/types'

definePageMeta({
    title: 'Simulation Activity Feed',
    layout: 'dashboard'
})

const router = useRouter()
const loggerStore = useLogger('simulation')

const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
        hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit'
    }) + '.' + new Date(dateString).getMilliseconds().toString().padStart(3, '0')
}

const getLevelColor = (level: string) => {
    switch(level) {
        case 'success': return 'success'
        case 'error': return 'error'
        case 'warn': 
        case 'warning': return 'warning'
        default: return 'primary'
    }
}

const columns = [
    {
        accessorKey: 'timestamp',
        header: 'Time',
        cell: ({ row }: { row: { original: AppLog }}) => h('span', { class: 'text-xs font-mono text-muted whitespace-nowrap' }, formatDate(row.original.timestamp))
    },
    {
        accessorKey: 'level',
        header: 'Level',
        cell: ({ row }: { row: { original: AppLog }}) => h(UBadge, { color: getLevelColor(row.original.level), variant: 'soft', size: 'xs', class: 'uppercase tracking-wider' }, () => row.original.level)
    },
    {
        accessorKey: 'state',
        header: 'Subsystem',
        cell: ({ row }: { row: { original: AppLog }}) => h('span', { class: 'text-sm font-semibold' }, row.original.state)
    },
    {
        accessorKey: 'message',
        header: 'Activity Log',
        cell: ({ row }: { row: { original: AppLog }}) => h('span', { class: 'text-sm' }, row.original.message)
    }
]
</script>

<template>
    <div class="flex-1 flex flex-col h-full max-w-7xl mx-auto w-full space-y-6">
        
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div class="flex items-center gap-4">
                <UButton icon="i-lucide-arrow-left" color="neutral" variant="ghost" @click="router.push('/admin/simulation')" />
                <div>
                    <h1 class="text-2xl font-bold flex items-center gap-3">
                        <UIcon name="i-lucide-activity" class="text-primary" />
                        Simulation Activity Feed
                    </h1>
                    <p class="text-muted text-sm mt-1">Real-time event stream generated by the automated engine.</p>
                </div>
            </div>
            <div class="flex items-center gap-3">
                <UButton label="Clear Logs" icon="i-lucide-trash-2" color="error" variant="soft" @click="loggerStore.clearLogs()" />
            </div>
        </div>

        <UCard :ui="{ body: 'p-0 sm:p-0' }" class="flex-1 overflow-hidden flex flex-col shadow-sm">
            <UTable 
                sticky 
                :data="loggerStore.logs.value" 
                :columns="columns"
                :ui="{ th: 'sm:px-6', td: 'sm:px-6 py-2 sm:py-2' }" 
                class="flex-1 overflow-y-auto scrollbar"
            >
                <template #empty>
                    <div class="p-12 text-center text-muted flex flex-col items-center justify-center">
                        <UIcon name="i-lucide-terminal" class="size-12 text-neutral-300 mb-4" />
                        <h3 class="text-lg font-semibold">No Simulation Activity</h3>
                        <p class="text-sm mt-1">Start the simulation engine to generate automated logs.</p>
                        <UButton label="Go to Engine Control" color="primary" class="mt-6" to="/admin/simulation" />
                    </div>
                </template>
            </UTable>
        </UCard>
    </div>
</template>
