import fs from 'fs';
import path from 'path';
import { marked } from 'marked';

const docsDir = path.join(process.cwd(), 'docs');
const outFile = path.join(process.cwd(), 'app', 'utils', 'docsData.ts');

const files = fs.readdirSync(docsDir);

const implementationDocs = [];
const walkthroughDocs = [];

for (const file of files) {
    if (!file.endsWith('.md')) continue;
    
    const content = fs.readFileSync(path.join(docsDir, file), 'utf8');
    const htmlContent = marked.parse(content);
    
    let label = file.replace('.md', '');
    
    const docObj = {
        label: label,
        content: htmlContent
    };

    if (file.toLowerCase().includes('implementation_plan')) {
        implementationDocs.push(docObj);
    } else if (file.toLowerCase().includes('walkthrough')) {
        walkthroughDocs.push(docObj);
    }
}

const outContent = `// Auto-generated by build_docs.js
export const implementationDocs = ${JSON.stringify(implementationDocs, null, 4)};

export const walkthroughDocs = ${JSON.stringify(walkthroughDocs, null, 4)};
`;

fs.writeFileSync(outFile, outContent);
console.log('Docs generated at app/utils/docsData.ts');
